name: Test

on:
  pull_request:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - 'LICENSE*'
      - '.github/workflows/precompile.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  linux:
    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: 25
          elixir-version: 1.14

      - name: Compile and Test
        run: |
          mix deps.get
          mix elixir_make.precompile
          mix test

  windows:
    runs-on: windows-latest
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.2.1"
          elixir-version: "1.16.0"

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Compile and Test
        shell: bash
        run: |
          mix deps.get
          mix elixir_make.precompile
          mix test

  macos:
    runs-on: macos-11
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v3

      - name: macOS setup
        run: |
          brew install erlang elixir
          mix local.hex --force
          mix local.rebar --force

      - name: Compile and Test
        run: |
          mix deps.get
          mix elixir_make.precompile
          mix test
